version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk

    working_directory: ~/project

    steps:
      - checkout

      # Install Chrome and ChromeDriver (for Selenium tests)
      - run:
          name: Install Chrome and ChromeDriver
          command: |
            curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee -a /etc/apt/sources.list.d/google-chrome.list
            sudo apt-get update && sudo apt-get install google-chrome-stable
            wget -N https://chromedriver.storage.googleapis.com/LATEST_RELEASE -O LATEST_RELEASE
            export CHROME_DRIVER_VERSION=$(cat LATEST_RELEASE)
            wget https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
            unzip chromedriver_linux64.zip
            sudo mv chromedriver /usr/local/bin

      # Install Maven
      - run:
          name: Install Maven
          command: |
            sudo apt-get install -f
            sudo apt-get install --reinstall java-common
            sudo apt-get remove ca-certificates-java
            sudo apt-get remove openjdk-11-jre-headless
            sudo apt-get install ca-certificates-java
            sudo apt-get install openjdk-11-jre-headless
            sudo apt-get install -y maven

      # Install dependencies and run tests
      - run:
          name: Build and Run Tests
          command: |
            mvn clean test

      # You can add additional steps as needed, such as generating reports, deploying, etc.

  # You can define additional jobs or workflows here as needed

workflows:
  version: 2
  build-deploy:
    jobs:
      - build